use crate::secret::SecretString;
use crate::{Config, ConfigError};
use std::io::Write;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpMode {
    Default,
    Current,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpTarget {
    Stdout,
    File(PathBuf),
    DefaultFile,
}

#[derive(Debug, Clone)]
pub struct DumpOptions {
    pub mode: DumpMode,
    pub target: DumpTarget,
    pub env_file: Option<PathBuf>,
}

const DEFAULT_FILENAME: &str = "aegis.toml";

impl DumpOptions {
    pub fn new(mode: DumpMode) -> Self {
        Self {
            mode,
            target: DumpTarget::DefaultFile,
            env_file: None,
        }
    }

    pub fn to_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.target = DumpTarget::File(path.into());
        self
    }

    pub fn to_stdout(mut self) -> Self {
        self.target = DumpTarget::Stdout;
        self
    }

    pub fn env_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.env_file = Some(path.into());
        self
    }
}

impl Config {
    pub fn dump(
        opts: &DumpOptions,
        current: Option<&Config>,
    ) -> Result<(), ConfigError> {
        let (toml_str, config_ref): (String, Option<&Config>) = match opts.mode {
            DumpMode::Default => (Config::default().to_toml()?, None),
            DumpMode::Current => {
                let config = current.ok_or(ConfigError::Validation(
                    "no current config available for dump".to_owned(),
                ))?;
                (config.to_toml()?, Some(config))
            }
        };

        let resolved_path = match &opts.target {
            DumpTarget::Stdout => {
                print!("{toml_str}");
                None
            }
            DumpTarget::File(path) => Some(path.clone()),
            DumpTarget::DefaultFile => Some(PathBuf::from(DEFAULT_FILENAME)),
        };

        if let Some(ref path) = resolved_path {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, &toml_str)?;
        }

        if let Some(cfg) = config_ref {
            let env_path = opts
                .env_file
                .as_deref()
                .unwrap_or(Path::new(".env.aegis"));

            cfg.dump_env(env_path)?;
        }

        Ok(())
    }

    pub fn dump_env(&self, path: &Path) -> Result<(), ConfigError> {
        let entries = self.collect_env_entries();
        if entries.is_empty() {
            return Ok(());
        }

        let mut output = String::from("# Auto-generated by aegis config dump\n");

        for (key, secret) in &entries {
            if secret.is_env_ref() {
                if let Ok(value) = secret.resolve() {
                    output.push_str(&format!("{key}={value}\n"));
                }
            } else if !secret.is_file_ref() {
                output.push_str(&format!("{key}={}\n", secret.raw()));
            }
        }

        if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
            std::fs::create_dir_all(parent)?;
        }

        append_or_create(path, &output)?;

        Ok(())
    }

    fn collect_env_entries(&self) -> Vec<(String, &SecretString)> {
        let mut entries = Vec::new();

        if let Some(key) = self.database.as_ref().and_then(|db| db.encryption_key.as_ref()) {
            entries.push(("AEGIS_DATABASE_ENCRYPTION_KEY".to_owned(), key));
        }

        if let Some(ref session) = self.session {
            entries.push(("AEGIS_SESSION_SECRET".to_owned(), &session.secret));
        }

        if let Some(ref pw) = self.email.smtp.password {
            entries.push(("AEGIS_EMAIL_SMTP_PASSWORD".to_owned(), pw));
        }

        if let Some(ref token) = self.api.internal.api_token {
            entries.push(("AEGIS_API_INTERNAL_TOKEN".to_owned(), token));
        }

        if let Some(ref key) = self.crypto.master_key {
            entries.push(("AEGIS_CRYPTO_MASTER_KEY".to_owned(), key));
        }

        if let Some(ref key) = self.crypto.jwt.private_key {
            entries.push(("AEGIS_CRYPTO_JWT_PRIVATE_KEY".to_owned(), key));
        }

        for (i, endpoint) in self.webhooks.endpoints.iter().enumerate() {
            if let Some(ref secret) = endpoint.secret {
                entries.push((format!("AEGIS_WEBHOOKS_ENDPOINT_{i}_SECRET"), secret));
            }
        }

        entries
    }

    pub fn default_env_template() -> String {
        let mut out = String::from("# Aegis environment variables\n");
        out.push_str("# Copy this file and fill in values\n\n");
        out.push_str("AEGIS_SESSION_SECRET=\n");
        out.push_str("AEGIS_DATABASE_ENCRYPTION_KEY=\n");
        out.push_str("AEGIS_EMAIL_SMTP_PASSWORD=\n");
        out.push_str("AEGIS_API_INTERNAL_TOKEN=\n");
        out.push_str("AEGIS_CRYPTO_MASTER_KEY=\n");
        out.push_str("AEGIS_CRYPTO_JWT_PRIVATE_KEY=\n");
        out
    }
}

fn append_or_create(path: &Path, content: &str) -> Result<(), ConfigError> {
    let existing = if path.exists() {
        std::fs::read_to_string(path)?
    } else {
        String::new()
    };

    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(true)
        .append(false)
        .open(path)?;

    if !existing.is_empty() {
        file.write_all(existing.as_bytes())?;
        if !existing.ends_with('\n') {
            file.write_all(b"\n")?;
        }
    }

    file.write_all(content.as_bytes())?;
    Ok(())
}
