use crate::ref_or::RefOr;
use crate::root::ConfigSrc;
use crate::{Config, ConfigError};
use std::io::Write;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpMode {
    Default,
    Current,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpTarget {
    Stdout,
    File(PathBuf),
    DefaultFile,
}

#[derive(Debug, Clone)]
pub struct DumpOptions {
    pub mode: DumpMode,
    pub target: DumpTarget,
    pub env_file: Option<PathBuf>,
}

const DEFAULT_FILENAME: &str = "aegis.toml";

impl DumpOptions {
    pub fn new(mode: DumpMode) -> Self {
        Self {
            mode,
            target: DumpTarget::DefaultFile,
            env_file: None,
        }
    }

    pub fn to_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.target = DumpTarget::File(path.into());
        self
    }

    pub fn to_stdout(mut self) -> Self {
        self.target = DumpTarget::Stdout;
        self
    }

    pub fn env_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.env_file = Some(path.into());
        self
    }
}

pub fn dump(
    opts: &DumpOptions,
    source: Option<&ConfigSrc>,
) -> Result<(), ConfigError> {
    let (toml_str, source_ref): (String, Option<&ConfigSrc>) = match opts.mode {
        DumpMode::Default => (ConfigSrc::default().to_toml()?, None),
        DumpMode::Current => {
            let src = source.ok_or(ConfigError::Validation(
                "no source config available for dump".to_owned(),
            ))?;
            (src.to_toml()?, Some(src))
        }
    };

    let resolved_path = match &opts.target {
        DumpTarget::Stdout => {
            print!("{toml_str}");
            None
        }
        DumpTarget::File(path) => Some(path.clone()),
        DumpTarget::DefaultFile => Some(PathBuf::from(DEFAULT_FILENAME)),
    };

    if let Some(ref path) = resolved_path {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, &toml_str)?;
    }

    if let Some(src) = source_ref {
        let env_path = opts
            .env_file
            .as_deref()
            .unwrap_or(Path::new(".env.aegis"));

        dump_env_from_source(src, env_path)?;
    }

    Ok(())
}

fn dump_env_from_source(source: &ConfigSrc, path: &Path) -> Result<(), ConfigError> {
    let entries = collect_env_refs(source);
    if entries.is_empty() {
        return Ok(());
    }

    let mut output = String::from("# Auto-generated by aegis config dump\n");

    for var in &entries {
        if let Ok(value) = std::env::var(var) {
            output.push_str(&format!("{var}={value}\n"));
        }
    }

    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent)?;
    }

    append_or_create(path, &output)?;

    Ok(())
}

fn collect_env_refs(source: &ConfigSrc) -> Vec<String> {
    let mut entries = Vec::new();

    if let Some(ref db) = source.database {
        if let Some(var) = db.url.env_var() {
            entries.push(var.to_owned());
        }
        if let Some(RefOr::Env(var)) = db.encryption_key.as_ref() {
            entries.push(var.clone());
        }
    }

    if let Some(ref session) = source.session
        && let Some(var) = session.secret.env_var()
    {
        entries.push(var.to_owned());
    }

    if let Some(var) = source.email.from_address.env_var() {
        entries.push(var.to_owned());
    }

    if let Some(var) = source.email.smtp.host.env_var() {
        entries.push(var.to_owned());
    }
    if let Some(var) = source.email.smtp.password.env_var() {
        entries.push(var.to_owned());
    }

    if let Some(RefOr::Env(var)) = source.api.internal.api_token.as_ref() {
        entries.push(var.clone());
    }

    if let Some(RefOr::Env(var)) = source.crypto.master_key.as_ref() {
        entries.push(var.clone());
    }

    if let Some(RefOr::Env(var)) = source.crypto.jwt.private_key.as_ref() {
        entries.push(var.clone());
    }
    if let Some(RefOr::Env(var)) = source.crypto.jwt.public_key.as_ref() {
        entries.push(var.clone());
    }

    for endpoint in &source.webhooks.endpoints {
        if let Some(RefOr::Env(var)) = endpoint.secret.as_ref() {
            entries.push(format!("AEGIS_WEBHOOK_{}", var));
            entries.push(var.clone());
        }
    }

    entries.sort();
    entries.dedup();
    entries
}

pub fn dump_env_resolved(config: &Config, path: &Path) -> Result<(), ConfigError> {
    let mut entries = Vec::new();

    if let Some(key) = config.database.as_ref().and_then(|db| db.encryption_key.as_ref()) {
        entries.push(("AEGIS_DATABASE_ENCRYPTION_KEY".to_owned(), key.raw().to_owned()));
    }

    if let Some(ref session) = config.session {
        entries.push(("AEGIS_SESSION_SECRET".to_owned(), session.secret.raw().to_owned()));
    }

    if !config.email.smtp.password.raw().is_empty() {
        entries.push(("AEGIS_EMAIL_SMTP_PASSWORD".to_owned(), config.email.smtp.password.raw().to_owned()));
    }

    if let Some(ref token) = config.api.internal.api_token {
        entries.push(("AEGIS_API_INTERNAL_TOKEN".to_owned(), token.raw().to_owned()));
    }

    if let Some(ref key) = config.crypto.master_key {
        entries.push(("AEGIS_CRYPTO_MASTER_KEY".to_owned(), key.raw().to_owned()));
    }

    if let Some(ref key) = config.crypto.jwt.private_key {
        entries.push(("AEGIS_CRYPTO_JWT_PRIVATE_KEY".to_owned(), key.raw().to_owned()));
    }

    if entries.is_empty() {
        return Ok(());
    }

    let mut output = String::from("# Auto-generated by aegis config env-export\n");

    for (key, value) in &entries {
        output.push_str(&format!("{key}={value}\n"));
    }

    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent)?;
    }

    append_or_create(path, &output)?;

    Ok(())
}

impl Config {
    pub fn default_env_template() -> String {
        let mut out = String::from("# Aegis environment variables\n");
        out.push_str("# Copy this file and fill in values\n\n");
        out.push_str("AEGIS_SESSION_SECRET=\n");
        out.push_str("AEGIS_DATABASE_URL=\n");
        out.push_str("AEGIS_DATABASE_ENCRYPTION_KEY=\n");
        out.push_str("AEGIS_EMAIL_SMTP_PASSWORD=\n");
        out.push_str("AEGIS_API_INTERNAL_TOKEN=\n");
        out.push_str("AEGIS_CRYPTO_MASTER_KEY=\n");
        out.push_str("AEGIS_CRYPTO_JWT_PRIVATE_KEY=\n");
        out
    }
}

fn append_or_create(path: &Path, content: &str) -> Result<(), ConfigError> {
    let existing = if path.exists() {
        std::fs::read_to_string(path)?
    } else {
        String::new()
    };

    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(true)
        .append(false)
        .open(path)?;

    if !existing.is_empty() {
        file.write_all(existing.as_bytes())?;
        if !existing.ends_with('\n') {
            file.write_all(b"\n")?;
        }
    }

    file.write_all(content.as_bytes())?;
    Ok(())
}
