use crate::ref_or::RefOr;
use crate::root::ConfigSrc;
use crate::{Config, ConfigError};
use std::io::Write;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpMode {
    Default,
    Current,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DumpTarget {
    Stdout,
    File(PathBuf),
    DefaultFile,
}

#[derive(Debug, Clone)]
pub struct DumpOptions {
    pub mode: DumpMode,
    pub target: DumpTarget,
    pub env_file: Option<PathBuf>,
}

const DEFAULT_FILENAME: &str = "aegis.toml";

impl DumpOptions {
    pub fn new(mode: DumpMode) -> Self {
        Self {
            mode,
            target: DumpTarget::DefaultFile,
            env_file: None,
        }
    }

    pub fn to_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.target = DumpTarget::File(path.into());
        self
    }

    pub fn to_stdout(mut self) -> Self {
        self.target = DumpTarget::Stdout;
        self
    }

    pub fn env_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.env_file = Some(path.into());
        self
    }
}

pub fn dump(
    opts: &DumpOptions,
    source: Option<&ConfigSrc>,
) -> Result<(), ConfigError> {
    let (toml_str, source_ref): (String, Option<&ConfigSrc>) = match opts.mode {
        DumpMode::Default => (ConfigSrc::default().to_toml()?, None),
        DumpMode::Current => {
            let src = source.ok_or(ConfigError::Validation(
                "no source config available for dump".to_owned(),
            ))?;
            (src.to_toml()?, Some(src))
        }
    };

    let resolved_path = match &opts.target {
        DumpTarget::Stdout => {
            print!("{toml_str}");
            None
        }
        DumpTarget::File(path) => Some(path.clone()),
        DumpTarget::DefaultFile => Some(PathBuf::from(DEFAULT_FILENAME)),
    };

    if let Some(ref path) = resolved_path {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, &toml_str)?;
    }

    if let Some(src) = source_ref {
        let env_path =
            opts.env_file.as_deref().unwrap_or(Path::new(".env.aegis"));

        dump_env_from_source(src, env_path)?;
    }

    Ok(())
}

fn dump_env_from_source(
    source: &ConfigSrc,
    path: &Path,
) -> Result<(), ConfigError> {
    let entries = collect_env_refs(source);
    if entries.is_empty() {
        return Ok(());
    }

    let mut output = String::from("# Auto-generated by aegis config dump\n");

    for var in &entries {
        if let Ok(value) = std::env::var(var) {
            output.push_str(&format!("{var}={value}\n"));
        }
    }

    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent)?;
    }

    append_or_create(path, &output)?;

    Ok(())
}

fn collect_env_refs_from_refor<T>(r: &RefOr<T>, entries: &mut Vec<String>) {
    if let RefOr::Env(var) = r {
        entries.push(var.clone());
    }
}

fn collect_env_refs(source: &ConfigSrc) -> Vec<String> {
    let mut entries = Vec::new();

    if let RefOr::Value(Some(db)) = &source.database {
        collect_env_refs_from_refor(&db.url, &mut entries);
        collect_env_refs_from_refor(&db.encryption_key, &mut entries);
    }

    if let RefOr::Value(Some(session)) = &source.session {
        collect_env_refs_from_refor(&session.secret, &mut entries);
    }

    if let RefOr::Value(email) = &source.email {
        collect_env_refs_from_refor(&email.from_address, &mut entries);
        if let RefOr::Value(smtp) = &email.smtp {
            collect_env_refs_from_refor(&smtp.host, &mut entries);
            collect_env_refs_from_refor(&smtp.password, &mut entries);
        }
    }

    if let RefOr::Value(api) = &source.api
        && let RefOr::Value(internal) = &api.internal
    {
        collect_env_refs_from_refor(&internal.api_token, &mut entries);
    }

    if let RefOr::Value(crypto) = &source.crypto {
        collect_env_refs_from_refor(&crypto.master_key, &mut entries);
        if let RefOr::Value(jwt) = &crypto.jwt {
            collect_env_refs_from_refor(&jwt.private_key, &mut entries);
            collect_env_refs_from_refor(&jwt.public_key, &mut entries);
        }
    }

    if let RefOr::Value(webhooks) = &source.webhooks
        && let RefOr::Value(eps) = &webhooks.endpoints
    {
        for e in eps {
            collect_env_refs_from_refor(&e.secret, &mut entries);
        }
    }

    entries.sort();
    entries.dedup();
    entries
}

pub fn dump_env_resolved(
    config: &Config,
    path: &Path,
) -> Result<(), ConfigError> {
    let mut entries = Vec::new();

    if let Some(db) = config.database.as_ref()
        && let Some(ref key) = db.encryption_key
        && !key.is_empty()
    {
        entries.push(("AEGIS_DATABASE_ENCRYPTION_KEY".to_owned(), key.clone()));
    }

    if let Some(ref session) = config.session
        && !session.secret.is_empty()
    {
        entries
            .push(("AEGIS_SESSION_SECRET".to_owned(), session.secret.clone()));
    }

    if !config.email.smtp.password.is_empty() {
        entries.push((
            "AEGIS_EMAIL_SMTP_PASSWORD".to_owned(),
            config.email.smtp.password.clone(),
        ));
    }

    if let Some(ref token) = config.api.internal.api_token {
        entries.push(("AEGIS_API_INTERNAL_TOKEN".to_owned(), token.clone()));
    }

    if let Some(ref key) = config.crypto.master_key {
        entries.push(("AEGIS_CRYPTO_MASTER_KEY".to_owned(), key.clone()));
    }

    if let Some(ref key) = config.crypto.jwt.private_key {
        entries.push(("AEGIS_CRYPTO_JWT_PRIVATE_KEY".to_owned(), key.clone()));
    }

    if let Some(ref key) = config.crypto.jwt.public_key {
        entries.push(("AEGIS_CRYPTO_JWT_PUBLIC_KEY".to_owned(), key.clone()));
    }

    if entries.is_empty() {
        return Ok(());
    }

    let mut output =
        String::from("# Auto-generated by aegis config env-export\n");

    for (key, value) in &entries {
        output.push_str(&format!("{key}={value}\n"));
    }

    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent)?;
    }

    append_or_create(path, &output)?;

    Ok(())
}

impl Config {
    pub fn default_env_template() -> String {
        let mut out = String::from("# Aegis environment variables\n");
        out.push_str("# Copy this file and fill in values\n\n");
        out.push_str("AEGIS_SESSION_SECRET=\n");
        out.push_str("AEGIS_DATABASE_URL=\n");
        out.push_str("AEGIS_DATABASE_ENCRYPTION_KEY=\n");
        out.push_str("AEGIS_EMAIL_SMTP_PASSWORD=\n");
        out.push_str("AEGIS_API_INTERNAL_TOKEN=\n");
        out.push_str("AEGIS_CRYPTO_MASTER_KEY=\n");
        out.push_str("AEGIS_CRYPTO_JWT_PRIVATE_KEY=\n");
        out.push_str("AEGIS_CRYPTO_JWT_PUBLIC_KEY=\n");
        out
    }
}

fn append_or_create(path: &Path, content: &str) -> Result<(), ConfigError> {
    let existing = if path.exists() {
        std::fs::read_to_string(path)?
    } else {
        String::new()
    };

    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(true)
        .append(false)
        .open(path)?;

    if !existing.is_empty() {
        file.write_all(existing.as_bytes())?;
        if !existing.ends_with('\n') {
            file.write_all(b"\n")?;
        }
    }

    file.write_all(content.as_bytes())?;
    Ok(())
}
